// ═══════════════════════════════════════════════════════════
//  dungeon-item-db.js  地下城物品元数据库
//  为地下城系统提供所有物品的名称、图标、类型信息
//  version: 2
// ═══════════════════════════════════════════════════════════

const DUNGEON_ITEM_DB = {
  // ── 收藏品 ──────────────────────────────────────────────
  col_broken_compass:    { name:'残破罗盘',        icon:'🧭', type:'collectible' },
  col_old_portrait:      { name:'陈旧画像',        icon:'🖼️', type:'collectible' },
  col_worn_sandal:       { name:'磨损布鞋',        icon:'👟', type:'collectible' },
  col_empty_jug:         { name:'空酒坛',          icon:'🏺', type:'collectible' },
  col_dice_set:          { name:'骰子套装',        icon:'🎲', type:'collectible' },
  col_copper_mirror:     { name:'铜镜',            icon:'🪞', type:'collectible' },
  col_clay_figurine:     { name:'泥塑人偶',        icon:'🎭', type:'collectible' },
  col_red_thread:        { name:'红线',            icon:'🧵', type:'collectible' },
  col_bronze_bell:       { name:'青铜钟',          icon:'🔔', type:'collectible' },
  col_music_score:       { name:'古曲谱',          icon:'🎼', type:'collectible' },
  col_jade_pendant:      { name:'玉佩',            icon:'🔹', type:'collectible' },
  col_chess_piece:       { name:'残棋',            icon:'♟️', type:'collectible' },
  col_ink_stick:         { name:'墨条',            icon:'🖌️', type:'collectible' },
  col_silver_hairpin:    { name:'银簪',            icon:'💎', type:'collectible' },
  col_sect_tablet:       { name:'门派令牌',        icon:'📿', type:'collectible' },
  col_letter_sealed:     { name:'封蜡信',          icon:'✉️', type:'collectible' },
  col_jade_ring:         { name:'玉戒指',          icon:'💍', type:'collectible' },
  col_tiger_seal:        { name:'虎符',            icon:'🐯', type:'collectible' },
  col_war_flag:          { name:'战旗',            icon:'🚩', type:'collectible' },
  col_ancient_coin:      { name:'古钱币',          icon:'🪙', type:'collectible' },
  col_anon_portrait:     { name:'无名画像',        icon:'🖼️', type:'collectible' },
  col_broken_sword:      { name:'断剑',            icon:'🗡️', type:'collectible' },
  col_cracked_bell:      { name:'裂纹铜铃',        icon:'🔔', type:'collectible' },
  col_jade_buddha:       { name:'玉佛',            icon:'🙏', type:'collectible' },
  col_moonstone:         { name:'月石',            icon:'🌙', type:'collectible' },
  col_phoenix_feather:   { name:'凤凰羽',          icon:'🪶', type:'collectible' },
  col_scroll_painting:   { name:'画卷残片',        icon:'🖼️', type:'collectible' },

  // ── 锻造材料 ────────────────────────────────────────────
  item_iron_ore:         { name:'铁矿石',          icon:'🪨', type:'material' },
  item_copper_ore:       { name:'铜矿石',          icon:'🪨', type:'material' },
  item_gold_ore:         { name:'金矿石',          icon:'🪨', type:'material' },
  item_cloth:            { name:'布料',            icon:'🧶', type:'material' },
  item_leather:          { name:'皮革',            icon:'🧥', type:'material' },
  item_copper_ingot:     { name:'铜锭',            icon:'🔶', type:'material' },
  item_copper_core:      { name:'铜芯',            icon:'⚙️', type:'material' },
  item_mechanism_core:   { name:'机关核心',        icon:'⚙️', type:'material' },
  item_mechanism_part:   { name:'机关零件',        icon:'🔩', type:'material' },
  item_bamboo:           { name:'竹子',            icon:'🎋', type:'material' },
  item_fur:              { name:'兽皮',            icon:'🧥', type:'material' },
  item_beast_bone:       { name:'兽骨',            icon:'🦴', type:'material' },
  item_ancient_bone:     { name:'古兽骨',          icon:'🦴', type:'material' },
  item_bone_fragment:    { name:'骨片',            icon:'🧊', type:'material' },

  // ── 草药药材 ─────────────────────────────────────────────
  item_herb_common:      { name:'普通草药',        icon:'🌿', type:'material' },
  item_herb_gancao:      { name:'甘草',            icon:'🌿', type:'material' },
  item_herb_rare:        { name:'珍稀灵草',        icon:'🌱', type:'material' },
  item_herb_renshen:     { name:'人参',            icon:'🌿', type:'material' },
  item_lotus_root:       { name:'莲藕',            icon:'🪷', type:'material' },
  item_bamboo_shoot:     { name:'竹笋',            icon:'🎍', type:'material' },
  item_vegetable_fresh:  { name:'新鲜蔬菜',        icon:'🥬', type:'material' },

  // ── 宝石晶石 ─────────────────────────────────────────────
  item_spirit_stone:     { name:'灵石',            icon:'💎', type:'material' },
  item_gem:              { name:'宝石',            icon:'💎', type:'material' },
  item_rare_gem:         { name:'稀有宝石',        icon:'💠', type:'material' },
  item_mythic_gem:       { name:'神话宝石',        icon:'🔮', type:'material' },
  item_fire_crystal:     { name:'火焰晶石',        icon:'🔥', type:'material' },
  item_ice_crystal:      { name:'寒冰晶石',        icon:'❄️', type:'material' },
  item_dark_crystal:     { name:'幽冥晶石',        icon:'🌑', type:'material' },
  item_sand_crystal:     { name:'流沙晶石',        icon:'🏜️', type:'material' },
  item_ancient_jade:     { name:'古玉',            icon:'🟢', type:'material' },
  item_pearl:            { name:'珍珠',            icon:'⚪', type:'material' },
  item_water_pearl:      { name:'水灵珠',          icon:'💧', type:'material' },
  item_dragon_pearl:     { name:'龙珠',            icon:'🐉', type:'material' },
  item_ghost_jade:       { name:'鬼玉',            icon:'👻', type:'material' },
  item_corrupt_evidence: { name:'腐败证物',        icon:'📜', type:'material' },

  // ── 精魄灵气 ─────────────────────────────────────────────
  item_chaos_essence:    { name:'混沌精魄',        icon:'🌀', type:'material' },
  item_fire_essence:     { name:'火焰精魄',        icon:'🔥', type:'material' },
  item_ice_essence:      { name:'寒冰精魄',        icon:'❄️', type:'material' },
  item_ghost_essence:    { name:'幽魂精魄',        icon:'👻', type:'material' },
  item_flame_essence:    { name:'烈焰精魄',        icon:'🔥', type:'material' },
  item_thunder_essence:  { name:'雷霆精魄',        icon:'⚡', type:'material' },
  item_miasma_essence:   { name:'瘴气',            icon:'☠️', type:'material' },
  item_guardian_essence: { name:'守护精魄',        icon:'🛡️', type:'material' },
  item_fire_core:        { name:'火核',            icon:'🔥', type:'material' },
  item_ice_core:         { name:'冰核',            icon:'❄️', type:'material' },
  item_thunder_core:     { name:'雷核',            icon:'⚡', type:'material' },
  item_ghost_bone:       { name:'鬼骨',            icon:'🦴', type:'material' },

  // ── 怪物掉落 ─────────────────────────────────────────────
  item_wolf_pelt:        { name:'狼皮',            icon:'🐺', type:'material' },
  item_wolf_fang:        { name:'狼牙',            icon:'🦷', type:'material' },
  item_alpha_pelt:       { name:'头狼皮',          icon:'🐺', type:'material' },
  item_alpha_fang:       { name:'头狼牙',          icon:'🦷', type:'material' },
  item_beast_core:       { name:'兽核',            icon:'💚', type:'material' },
  item_boar_meat:        { name:'野猪肉',          icon:'🥩', type:'material' },
  item_boar_tusk:        { name:'野猪獠牙',        icon:'🦷', type:'material' },
  item_tiger_skin:       { name:'虎皮',            icon:'🐯', type:'material' },
  item_tiger_bone:       { name:'虎骨',            icon:'🦴', type:'material' },
  item_bear_paw:         { name:'熊掌',            icon:'🐾', type:'material' },
  item_bear_gall:        { name:'熊胆',            icon:'🫀', type:'material' },
  item_leopard_pelt:     { name:'豹皮',           icon:'🐆', type:'material' },
  item_ice_wolf_pelt:    { name:'冰狼皮',          icon:'🐺', type:'material' },
  item_frost_fang:       { name:'冰狼牙',          icon:'🦷', type:'material' },
  item_eagle_feather:    { name:'鹰羽',            icon:'🪶', type:'material' },
  item_eagle_talon:      { name:'鹰爪',            icon:'🦅', type:'material' },
  item_lizard_scale:     { name:'蜥蜴鳞',          icon:'🦎', type:'material' },
  item_lizard_tail:      { name:'蜥尾',            icon:'🦎', type:'material' },
  item_snake_skin:       { name:'蛇皮',            icon:'🐍', type:'material' },
  item_snake_venom:      { name:'蛇毒',            icon:'🐍', type:'material' },
  item_spider_silk:      { name:'蛛丝',            icon:'🕷️', type:'material' },
  item_spider_venom:     { name:'蛛毒',            icon:'🕷️', type:'material' },
  item_dragon_scale:     { name:'龙鳞',            icon:'🐉', type:'material' },
  item_beast_fang:       { name:'兽牙',            icon:'🦷', type:'material' },
  item_beast_pelt:       { name:'兽皮',            icon:'🧥', type:'material' },
  item_white_scale:      { name:'白鳞',            icon:'⚪', type:'material' },
  item_shark_tooth:      { name:'鲨齿',            icon:'🦈', type:'material' },
  item_crab_shell:       { name:'蟹壳',            icon:'🦀', type:'material' },
  item_shrimp_shell:     { name:'虾壳',            icon:'🦐', type:'material' },
  item_fish_scale:       { name:'鱼鳞',            icon:'🐟', type:'material' },
  item_meat_rabbit:      { name:'兔肉',            icon:'🐰', type:'material' },
  item_wild_meat:        { name:'野味',            icon:'🥩', type:'material' },

  // ── 毒物相关 ─────────────────────────────────────────────
  item_poison_gland:      { name:'毒腺',            icon:'☠️', type:'material' },
  item_antidote:          { name:'解毒药',          icon:'💊', type:'consumable' },
  item_poison_dart:       { name:'毒针',            icon:'💉', type:'material' },
  item_dark_token:        { name:'黑道令牌',        icon:'🖤', type:'material' },
  item_queen_venom:       { name:'蛊后毒',          icon:'🐛', type:'material' },
  item_gu_essence:        { name:'蛊虫精魄',        icon:'🐛', type:'material' },
  item_gu_king_heart:     { name:'蛊王心',          icon:'💀', type:'material' },
  item_gu_poison:         { name:'蛊毒',            icon:'🐛', type:'material' },

  // ── 丹药 ─────────────────────────────────────────────────
  item_elixir_low:        { name:'下品丹药',        icon:'💊', type:'consumable' },
  item_elixir_mid:        { name:'中品丹药',        icon:'💊', type:'consumable' },
  item_elixir_high:       { name:'上品丹药',        icon:'💊', type:'consumable' },
  item_charm_elixir:      { name:'媚药',            icon:'💊', type:'consumable' },

  // ── 武器（战利品）────────────────────────────────────────
  item_hunter_bow:        { name:'猎弓',            icon:'🏹', type:'weapon' },
  item_crude_blade:       { name:'粗制刀',          icon:'🗡️', type:'weapon' },
  item_assassin_blade:    { name:'刺客短刃',        icon:'🗡️', type:'weapon' },
  item_sword_shard:       { name:'断剑碎片',        icon:'🗡️', type:'material' },
  item_ancient_sword_frag:{ name:'古剑残片',        icon:'🗡️', type:'material' },

  // ── 令牌印章 ─────────────────────────────────────────────
  item_bandit_seal:       { name:'山贼印章',        icon:'📮', type:'material' },
  item_sect_recall:       { name:'门派回令',        icon:'🏮', type:'consumable', desc:'消耗后可瞬间传送回本门总舵' },
  item_haisha_token:       { name:'海鲨令牌',        icon:'🦈', type:'material' },
  item_xuegu_emblem:       { name:'血骨门徽',        icon:'🩸', type:'material' },
  item_xuanming_code:      { name:'玄冥蛊符',        icon:'📜', type:'material' },
  item_iron_token:         { name:'铁制令牌',        icon:'🔖', type:'material' },
  item_copper_coin:        { name:'铜钱',            icon:'🪙', type:'material' },
  item_blade_token:        { name:'刀客令牌',        icon:'🗡️', type:'material' },
  item_fire_token:         { name:'烈焰令牌',        icon:'🔥', type:'material' },
  item_devil_token:        { name:'邪魔令牌',        icon:'👹', type:'material' },
  item_invader_token:      { name:'侵略者令牌',      icon:'⚔️', type:'material' },
  item_smuggler_map:       { name:'走私地图',        icon:'🗺️', type:'material' },
  item_wild_sect_token:    { name:'草莽令牌',        icon:'⚔️', type:'material' },
  item_cult_relic:         { name:'邪教遗物',        icon:'☠️', type:'material' },
  item_imperial_token:     { name:'朝廷令牌',        icon:'🏛️', type:'material' },
  item_bounty_scroll:      { name:'悬赏令',          icon:'📜', type:'material' },
  item_sutra:              { name:'经书残卷',        icon:'📿', type:'material' },
  item_stolen_scripture:   { name:'被盗经文',        icon:'📜', type:'material' },
  item_dark_taoist_manual: { name:'邪道秘籍',        icon:'📖', type:'material' },
  item_tomb_relic:         { name:'墓穴遗物',        icon:'⚱️', type:'material' },
  item_ancient_artifact:   { name:'远古遗物',        icon:'🏺', type:'material' },
  item_xia_relic:          { name:'侠客遗物',        icon:'⚔️', type:'material' },
  item_pagoda_relic:       { name:'佛塔遗物',        icon:'🏯', type:'material' },
  item_buddhist_relic:     { name:'佛教圣物',        icon:'🙏', type:'material' },
  item_canal_token:        { name:'漕帮令牌',        icon:'🚢', type:'material' },
  item_damp_cargo:         { name:'潮湿货物',        icon:'📦', type:'material' },
  item_smuggled_goods:     { name:'走私货物',        icon:'📦', type:'material' },
  item_luxury_goods:       { name:'奢侈品',          icon:'💎', type:'material' },
  item_western_silk:       { name:'西域丝绸',        icon:'🧶', type:'material' },
  item_local_specialty:     { name:'本地特产',        icon:'🎁', type:'material' },
  item_leftover_food:      { name:'残羹剩饭',        icon:'🍖', type:'material' },
  item_fish:               { name:'鲜鱼',            icon:'🐟', type:'material' },
  item_ink_songyan:        { name:'松烟墨',          icon:'🖌️', type:'material' },
  item_peach_blossom:      { name:'桃花',            icon:'🌸', type:'material' },
  item_horse_hair:        { name:'马鬃',            icon:'🐴', type:'material' },
  item_snake_demon_pearl:  { name:'蛇妖内丹',        icon:'🐍', type:'material' },
  item_water_dragon_pearl: { name:'水龙珠',          icon:'💧', type:'material' },
  item_yin_yang_orb:       { name:'阴阳珠',          icon:'☯️', type:'material' },
  item_ghost_king_core:    { name:'鬼王核心',        icon:'👻', type:'material' },
  item_miasma_core:        { name:'瘴气核心',        icon:'☠️', type:'material' },
  item_purgatory_flame:    { name:'炼狱火',          icon:'🔥', type:'material' },
  item_dice:               { name:'骰子',            icon:'🎲', type:'material' },
  item_gold_dice:          { name:'金骰子',          icon:'🎲', type:'material' },

  // ── 门派令牌（地下城相关）────────────────────────────────
  item_shaolin_seal:       { name:'少林寺印',        icon:'🛕', type:'material' },
  item_wudang_token:       { name:'武当令牌',        icon:'⚔️', type:'material' },
  item_huashan_token:      { name:'华山令牌',        icon:'⚔️', type:'material' },
  item_kunlun_token:       { name:'昆仑令牌',        icon:'⚔️', type:'material' },
  item_tibet_token:        { name:'西藏令牌',        icon:'⚔️', type:'material' },
  item_mingjiao_token:     { name:'明教令牌',        icon:'🔥', type:'material' },
  item_riyue_token:        { name:'日月令牌',        icon:'☀️', type:'material' },
  item_peach_island_token: { name:'桃花岛令牌',       icon:'🌸', type:'material' },
  item_sword_island_token: { name:'侠客岛令牌',      icon:'⚔️', type:'material' },
  item_jade_token_dragon:  { name:'玉龙令牌',        icon:'🐉', type:'material' },
  item_taoist_charm:       { name:'道符',            icon:'📜', type:'material' },
  item_zombie_flesh:       { name:'僵尸肉',          icon:'🧟', type:'material' },
  item_ore_iron:           { name:'铁矿',            icon:'🪨', type:'material' },
  item_river_mud:          { name:'河泥',            icon:'🟤', type:'material' },
  item_manual_rare:        { name:'稀有秘籍',        icon:'📖', type:'material' },
  item_manual_complete:    { name:'完整秘籍',        icon:'📚', type:'material' },
  item_coral_branch:       { name:'珊瑚枝',          icon:'🪸', type:'material' },
  item_ancient_manual:     { name:'古籍',            icon:'📜', type:'material' },

  // ── 地下城事件特殊物品 ───────────────────────────────────
  item_inscription_rubbing:   { name:'残破碑文拓本',    icon:'📜', type:'consumable', desc:'石壁上古老碑文的拓印，记载着一门武学的修炼要诀。' },
  item_trap_parts:           { name:'陷阱零件',        icon:'⚙️', type:'material', desc:'从精巧机关陷阱中拆解出的零件。' },
  item_poison_extract:       { name:'毒雾精华',        icon:'☠️', type:'material', desc:'从剧毒雾气中采集的浓缩毒素。' },
  item_blood_bone_token:     { name:'血骨令',          icon:'🩸', type:'material', desc:'染血的骨制令牌，刻有神秘符号。' },

  // ── 武器掉落（武器类型）──────────────────────────────────
  wep_uc_dao:              { name:'粗制短刀',        icon:'🗡️', type:'weapon' },
  wep_uc_spear:            { name:'粗制长矛',        icon:'🔱', type:'weapon' },
  wep_iron_sword:          { name:'铁剑',            icon:'⚔️', type:'weapon' },
  wep_rare_sword:          { name:'精钢剑',          icon:'⚔️', type:'weapon' },
  wep_rare_spear:          { name:'精钢长矛',        icon:'🔱', type:'weapon' },
  wep_rare_dagger:         { name:'精钢匕首',        icon:'🗡️', type:'weapon' },
  wep_rare_xuegu_blade:    { name:'血骨刀',          icon:'🗡️', type:'weapon' },
  wep_rare_dark_blade:     { name:'玄冥刀',          icon:'🗡️', type:'weapon' },
  wep_ghost_blade:         { name:'鬼刃',            icon:'🗡️', type:'weapon' },
  wep_blood_saber:         { name:'血刀',            icon:'🗡️', type:'weapon' },
  wep_epic_sword:          { name:'玄铁剑',          icon:'⚔️', type:'weapon' },
  wep_epic_dagger:         { name:'寒匕',            icon:'🗡️', type:'weapon' },
  wep_epic_dark_blade:     { name:'幽冥刀',          icon:'🗡️', type:'weapon' },
  wep_epic_devil_blade:    { name:'魔刀',            icon:'🗡️', type:'weapon' },
  wep_epic_fire_blade:     { name:'烈焰刀',          icon:'🗡️', type:'weapon' },
  wep_epic_ghost_blade:    { name:'鬼魄刀',          icon:'🗡️', type:'weapon' },
  wep_epic_xuegu_blade:    { name:'血骨战刀',        icon:'🗡️', type:'weapon' },
  wep_legendary_sword:     { name:'倚天剑',          icon:'⚔️', type:'weapon' },
  wep_sea_king_crown:      { name:'海王冠',          icon:'👑', type:'weapon' },
};
